# Imports

In [1]:
import numpy as np
import tensorflow as tf

# Constants

In [6]:
X_TRAIN_PATH = 'MNIST/digit_xtrain.csv'
Y_TRAIN_PATH = 'MNIST/digit_ytrain.csv'

LOGGING_PATH = 'tensorboard_mnist_digit_logs/'
saved_models = "saved_models/"

NR_CLASSES = 10
VALIDATION_SIZE = 10000
IMAGE_WIDTH = 28
IMAGE_HEIGHT = 28
CHANNELS = 1
TOTAL_INPUTS = IMAGE_WIDTH*IMAGE_HEIGHT*CHANNELS


nr_epochs = 70
learning_rate = 5e-4

n_hidden1 = 512
n_hidden2 = 64

X_TEST_PATH = 'MNIST/load_xtest.csv'
Y_TEST_PATH = 'MNIST/load_ytest.csv'

# Load and Preprocess Data

In [7]:
# Re-scale features - aby sme dostali hodnoty 0 - 1 a nie 0 - 255, ako je to teraz
def preprocess_data(x, y):
    # Normalize images
    x = x / 255.0

    # One-hot encode labels
    y = tf.one_hot(y.astype(np.int32), depth=NR_CLASSES)
    return x, y

In [8]:
def get_data():
    # Load data from files
    y_test = np.loadtxt(Y_TEST_PATH, delimiter=',', dtype=int)
    x_test = np.loadtxt(X_TEST_PATH, delimiter=',', dtype=float)

    # Preprocess the data
    x_test, y_test = preprocess_data(x_test, y_test)
    return x_test, y_test



In [9]:
x_test, y_test = get_data()
print(f'Shape of x_test {x_test.shape}')
print(f'Shape of y_test {x_test.shape}')

Shape of x_test (10000, 784)
Shape of y_test (10000, 784)


# Load the Model

```
tf.compat.v1.saved_model.load(sess,
                           [tag_constants.SERVING],
                           EXPORT_DIR)
```

In [10]:
# Specify the path to the saved model directory
model_path = "saved_models/"

# Load the saved model
loaded_model = tf.saved_model.load(model_path)

# Test data

In [11]:
# Testing
def test_data(model):
    # Make predictions on the test data
    predictions = model(x_test)
    # Calculate accuracy
    test_accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(predictions, axis=1), tf.argmax(y_test, axis=1)), tf.float32))
    # Convert accuracy to a percentage and round to two decimal places
    accuracy_percent = tf.round(test_accuracy * 100, 2)
    # Print the accuracy as a percentage
    print(f"Accuracy: {accuracy_percent}%")
    print(f'Accuracy on test set is {test_accuracy:0.2%}')

In [12]:
test_data(loaded_model)

Accuracy: 11.0%
Accuracy on test set is 11.39%


In [13]:
y_test[:5]

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

In [15]:
predictions = loaded_model(x_test)

In [16]:
predictions[:5]

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[-0.13792796,  0.1501318 , -0.21788621, -0.12735713,  0.0334333 ,
         0.10202569, -0.12212468, -0.08454008, -0.51458585,  0.08594806],
       [-0.13872986,  0.1610417 , -0.19747278, -0.13731843,  0.00229461,
         0.10634296, -0.07268298, -0.163056  , -0.49889255,  0.04274086],
       [-0.15257603,  0.19750708, -0.22316706, -0.1397904 ,  0.03882719,
         0.10127033, -0.09527921, -0.12217683, -0.51457614,  0.07024723],
       [-0.10488565,  0.13022897, -0.23056272, -0.14715251,  0.01829705,
         0.10172514, -0.08512358, -0.12836945, -0.5206715 ,  0.06650034],
       [-0.14091158,  0.14869489, -0.21001488, -0.14567211,  0.06496836,
         0.08819276, -0.08325665, -0.12131174, -0.5113587 ,  0.0778081 ]],
      dtype=float32)>

# Run Session & Make Prediction

# Check Results

# Cleanup